### ISSUE TITLE
 How to read data from non-standard slide libraries

### ISSUE THREAD

**Issue by syy-create** [MathOnco/valis#117]
Thank you very much for your work. But one question is, can I read images that non-standard slide libraries can read? I want to register some images in KFB format, but the slide standard library cannot read them, so I would like to ask if you have any suggestions?
By the way, I have a library that can read kfb. My original plan was to replace the import slide in the code with kfbslide, but unfortunately, I did not find any replaceable options in the import, so I would like to seek your help or advice.
Best wishes.

**Comment by cdgatenbee** [comment]
Hi @syy-create,
It is possible to create custom slide readers to support formats valis cannot currently read. To do this, you would need to sublcass the [slide_io.SlideReader](https://valis.readthedocs.io/en/latest/slide_io.html#valis.slide_io.SlideReader). It needs to be able to convert the slide to numpy arrays ([slide2image](https://valis.readthedocs.io/en/latest/slide_io.html#valis.slide_io.SlideReader.slide2image)), `pyvips.Image` objects ([slide2vips)](https://valis.readthedocs.io/en/latest/slide_io.html#valis.slide_io.SlideReader.slide2vips), and extract metadata (See the [Metadata)](https://valis.readthedocs.io/en/latest/slide_io.html#metadata) class for the information that is usually collected). It looks like much of this is already being done by `kfbslide`, so this custom reader would probably mostly be a wrapper that allows valis to use `kfbslide`. I don't have any kbf images to work on this with, but I could offer advice if you run into issues creating this reader. 

Best,
-Chandler
