### ISSUE TITLE
large tiff output

### ISSUE THREAD

**Issue by lingxitong** [MathOnco/valis#124]
hello,nice work,when I save tiff，the file can be 100+GB，so I set Q =5，tiff wil be 3GB，But has low resolution than origin svs,so How can I get high resolution and low GB files？thanks

**Comment by Justin-Krieg** [comment]
I'm not associated with Valis, but I used it frequently. @cdgatenbee might have some different opinions, but in my experience you have to decide on a compression factor (Q) that balances between quality and file size. I generally use Q=85, but it depends on your research question and requirements, ie. how much quality do you need?. It might be worthwhile trying different compression file types such as jpeg or jp2k. The other thing to consider is setting the crop="overlap" as this will remove any part that doesn't have overlapping images. Finally, consider dropping duplicate DAPI channels (drop_duplicates=True) as means of reducing file sizes. The [examples](https://valis.readthedocs.io/en/latest/examples.html) on the readthedocs page are handy for understanding how to implement these.

**Comment by cdgatenbee** [comment]
Hi @lingxitong,
@Justin-Krieg has offered some great advice and insights (thank you!). I just want to add a bit more about trying a compression method, which I think could be a quick and easy way to reduce the file size. The default compression algorithm is "lzw", which has the benefit of working well with most datatypes, but has the downside that it doesn't offer a huge decrease in file size. However, if you are aligning RGB images, setting `compression="jpeg"` or  `compression="jp2k"` should reduce the file size quite a bit, especially if you are setting `Q` less than 100. You can still use jpeg or jp2k compression if you're aligning IF images, but it may result in some loss of precision if the original images aren't uint8. Besides that, I think all of @Justin-Krieg 's suggestions are great and should go a long way in reducing the file size. If you run into any other issues or have any other questions, please don't hesitate to ask.

Best,
-Chandler
