### ISSUE TITLE
valis requires and outdated version of pydantic through ome-types

### ISSUE THREAD

**Issue by iRyoka** [MathOnco/valis#130]
The latest release of valis-wsi installed by pip results in ome-types==0.3.4 being installed. This in turn requires a v1-era pydantic, which is  outdated. The latest release ome-types==0.5.1.post1 supports both pydantic v1 and v2 through pydantic_compat. This is a major imporovement in compatibility of ome-types which is not yet adopted by valis-wsi.

Could you possibly update to the latest ome-types?
![2024-05-31_22-34-26 (2)](https://github.com/MathOnco/valis/assets/795201/9ff5a2cd-e1eb-498e-a7e9-813eb2165e84)
![2024-05-31_22-38-16](https://github.com/MathOnco/valis/assets/795201/7b06acb9-f7fb-4f0e-88a9-5e8d2cd4eb7e)

**Comment by cdgatenbee** [comment]
Hi @iRyoka, 

Thanks for bringing this to my attention. I'll be sure to update the `pyproject.toml` and `poetry.lock` files to have the latest version of ome-types in the next update, which should be pretty soon.

Best,
-Chandler

**Comment by cdgatenbee** [comment]
Hi @iRyoka, 
Just wanted to let you know the latest release of valis (1.1.0) has updated ome-types to 0.5.1.post1. I'll go ahead and close the issue, but if you run into any problems, please let me know.

Best,
-Chandler
