### ISSUE TITLE
Save only one Tiff

### ISSUE THREAD

**Issue by lingxitong** [MathOnco/valis#155]
Hello，I have HE and CD-31 to do registeration，But I only want to save CD-31 tiff，can you tell
 me how to do this? thanks

**Comment by cdgatenbee** [comment]
Hi @lingxitong,
You can do this by calling the `warp_and_save_slide` method of the `Slide` object associated with the CD31 image. For example, that might look something like this

```
# Get Slide associated with CD31 image
cd31_f = "CD-31.tiff"
slide_obj = registrar.get_slide(cd31_f)

# Warp and save to `dst_f`
slide_obj.warp_and_save_slide(dst_f)
```

Best,
-Chandler
