### ISSUE TITLE
Don't see stacked images saved as OME-TIFF

### ISSUE THREAD

**Issue by WillYe45** [MathOnco/valis#169]
Hi, I have been running the pipeline several times for alignment, however, after running, I only see my original input svs files being converted to OME-TIFF format, but I do not see the stacked images. The pipeline did output the thumbnails of those stacked images, and I am wondering if there is something wrong with my code. My code looks like this: 
# Load the necessary environment
eval "$(/path/to/miniconda/bin/conda shell.bash hook)" 
source activate Valis  

# Define input and output directories 
slide_src_dir="/path/to/slides"
results_dst_dir="/path/to/output/results"
registered_slide_dst_dir="/path/to/output/registered_slides"

# Ensure output directories exist
[ ! -d "$results_dst_dir" ] && mkdir -p "$results_dst_dir"
[ ! -d "$registered_slide_dst_dir" ] && mkdir -p "$registered_slide_dst_dir"

# Run the Valis alignment
python -c '
from valis import registration

# Reference slide
reference_slide = "reference_slide_name.svs"

# Initialize registration
registrar = registration.Valis(
    "'"$slide_src_dir"'", 
    "'"$results_dst_dir"'", 
    reference_img_f=reference_slide, 
    max_processed_image_dim_px=300
)

# Perform registration
print("Running registration...")
rigid_registrar, non_rigid_registrar, error_df = registrar.register()
registrar.register_micro(max_non_rigid_registration_dim_px=2000, align_to_reference=True)

# Warp and save slides
print("Warping and saving slides...")
registrar.warp_and_save_slides("'"$registered_slide_dst_dir"'", crop="overlap")

# Kill the JVM
registration.kill_jvm()
'
I would greatly appreciate any help, thank you in advance.

**Comment by cdgatenbee** [comment]
Hi @WillYe45,
The code looks correct, as `registrar.warp_and_save_slides` should save each registered image as an ome.tiff (one per svs). But could you please clarify your question for me? Is the issue that the saved ome.tiffs look the same as the original svs, as if they are not being warped? Or, is that that only one of the svs images is being saved? Or, finally, were you expecting that there would be a single ome.tiff that contains all of the aligned images, each as a "series"?

Best,
-Chandler

**Comment by WillYe45** [comment]
Hi Chandler,

my question was that for example, I have 3 original images in svs format, and after the pipeline, I also see 4 thumb nail pictures in the /overlaps folder. However, in the registered slide folder, I only see those 3 original images saved as ome-tiff format, without the overlapped images. I am wondering if this pipeline is also supposed to save those aligned images as ome-tiff for downstream analysis? It is hard to work on the thumbnails as they are low resolution png files.

Best,
Will
