### ISSUE TITLE
What is "register.py" in docker command?

### ISSUE THREAD

**Issue by pimooook** [MathOnco/valis#174]
docker run --memory=20g  -v "$HOME:$HOME" cdgatenbee/valis-wsi python3 register.py

Hello, I want to run this code with docker, but I don't know where "register.py" is. Do I need to write it by myself? Could you give me some examples?

**Comment by cdgatenbee** [comment]
Hi @pimooook, 
Yes, you would need to write `register.py` yourself, but it can be a pretty simple script. It just needs to read in command line arguments, parse them, and then use those arguments to perform registration. Here is an example where you would pass in the source and destination directories:

```
from valis import registration
import argparse

if __name__ == "__main__":
    # Parse command line arguments
    parser = argparse.ArgumentParser(description='align images')
    parser.add_argument('-src_dir', type=str, help='folder containing images to align')
    parser.add_argument('-dst_dir', type=str, help='where to save the results')

    args = vars(parser.parse_args())

    src_dir = args["src_dir"]
    dst_dir = args["dst_dir"]
    
    # Register images using command line arguments
    registrar = registration.Valis(src_dir, dst_dir)
    rigid_registrar, non_rigid_registrar, error_df = registrar.register()

```

If that is your `register.py`, then the command you would use for Docker would need to include `src_dir` and `dst_dir`

```
docker run --memory=20g -v "$HOME:$HOME" cdgatenbee/valis-wsi python3 register.py -src_dir "path/to/images/" -dst_dir "where/to/save/results"
```

You can then change `register.py` to suit your needs, such adding code to save the ome.tiffs, using custom image processors, etc... Hopefully that helps, and if you have any questions, please let me know.

Best,
-Chandler
