### ISSUE TITLE
Totally wrong with roi mask detection

### ISSUE THREAD

**Issue by pimooook** [MathOnco/valis#175]
![MY019-20241025-153051 ibl](https://github.com/user-attachments/assets/8b64ab94-a2b8-431d-a112-a3b6cc5ff8ff)
![QQ_1733911066590](https://github.com/user-attachments/assets/1cb1662b-f0a6-48a1-87dd-11b21ee32684)
![MY022-20241025-154057 ibl](https://github.com/user-attachments/assets/9f2efa24-c6ed-49f4-87df-dc84e780228e)

I have four tiff to be registered. However, the output masks are totally wrong. They focus on the mark on the slide.

**Comment by pimooook** [comment]
How can I provide masks by myself?

**Comment by cdgatenbee** [comment]
Hi @pimooook, 
That does look pretty bad. Are you using the Docker image? If so, there is an issue right now where it isn't creating masks correctly. However, you can overcome this by creating a custom `ImageProcesser` object that creates masks using a different method. In example script below, I've created `CustomProcessor`, which has two methods to create masks: `create_roi_mask` uses the previous version of valis' method of creating masks; `create_mask_for_full_image` creates a mask that just covers the image, which is essentially the same as not using a mask at all. You can change which approach you'd like to use by editing `CustomProcessor.create_mask`, which is what gets called when valis creates masks for each image. If you'd like, you can also change `CustomProcessor.create_mask` to make masks using a custom method. You can then use this custom `ImageProcesser` by passing it to the `brightfield_processing_cls` argument when you call `Valis.register`. All together, the code would look something like this: 

```

import numpy as np
from valis import registration, preprocessing


class CustomProcessor(preprocessing.OD):

    def __init__(self, image, src_f, level, series, *args, **kwargs):
        super().__init__(image=image, src_f=src_f, level=level,
                         series=series, *args, **kwargs)

    def create_roi_mask(self):
        """
        Create mask that covers only the tissue
        """

        tissue_mask, _ = preprocessing.create_tissue_mask_from_rgb(self.image)
        mask = preprocessing.mask2bbox_mask(tissue_mask)

        return mask

    def create_mask_for_full_image(self):
        """
        Create mask that covers the whole image
        """

        mask = np.full(self.image.shape[0:2], 255, dtype=np.uint8)

        return mask

    def create_mask(self):
        """
        Create tissue mask here. This what actually gets used when valis creates masks for each image
        """

        mask = self.create_mask_for_full_image() # Use this to if you want to use the whole image
        # mask = self.create_roi_mask() # Use this if you want to try to get a mask only around the tissue

        return mask


    def process_image(self, *args, **kwargs):
        """
        Process image to uint8 single channel image
        Currently uses parent method, but can be changed
        """

        processed_image = super().process_image(*args, **kwargs)

        return processed_image


custom_processor_kwargs = {} # Can be dictionary with keyword: value pairs to pass to CustomProcessor.process_image
registrar = registration.Valis(src_dir, dst_dir)
rigid_registrar, non_rigid_registrar, error_df = registrar.register(brightfield_processing_cls=CustomProcessor, brightfield_processing_kwargs=custom_processor_kwargs)

```

Please try that out and let me know if it works for you.

Best,
-Chandler

**Comment by pimooook** [comment]
Thank you very much! This really helps a lot. I'm not using docker. The code is directly written with python. After define my own CustomProcessor, the data can be well registered.
