### ISSUE TITLE
keep original colors for channels if they are within metadata. input channel color map as option

### ISSUE THREAD

**Issue by snibbor** [MathOnco/valis#23]
Hi,

This is nitpicking, but I do not like how VALIS changes the colors of the channels for my immunofluorescent OME-TIFFs. 

I would like for there to be an option to keep the original channel colors or input a custom color map. I will try to play around to see if I can get something to work, but just posting it here as a feature request. Maybe there is a VALIS parameter/solution I'm not familiar with.

**Comment by cdgatenbee** [comment]
Hi @crobbins327,
Thanks for the suggestion, that seems like a useful feature. If channel colors are present in the original image's metadata, then it seems like it shouldn't be too difficult to transfer that information to the new ome-xml. I can also add a channel color argument to the save slide function that will take a list of colors. I'll add these features to the todo list for the next update. 

Best,
Chandler

**Comment by cdgatenbee** [comment]
Hi @crobbins327, 
Finally pushed the update with this feature :) The default behavior should now be to transfer the original colors, but you can also provide a colormap to the `warp_and_save_slide` function, where the key is the channel name (which is recorded in each `Slide.reader.metadata.channel_names` attribute) and the value is the RGB tuple (0-255). I was able to test it on a few images here and so I'll close the issue, but if you run into any problems let me know and we can reopen this. Also, thanks again for the suggestion, it makes a lot more sense than the previous implementation.

Best,
-Chandler

**Comment by crobbins327** [comment]
@cdgatenbee awesome Chandler! I could see how the perceptual color map is really useful for high-plex IF images like cyclic IF, but I like that the default behavior won't change the original channel color data now. 

Can't wait to try it out on my next batch of images :)
