### ISSUE TITLE
Intermittent artifacts introduced in micro-registration step

### ISSUE THREAD

**Issue by NichD** [MathOnco/valis#30]
Greetings - I've been exploring VALIS for a month now and I've found it to be a very robust registration tool overall. Thank you and kudos for all the hard work!

I have encountered one issue that is intermittent. Most data I processed did not encounter this, but on a few datasets, there seems to be some artifacts introduced in the micro-registration step. I've included samples of the PNGs generated by VALIS for reference. Between the non-rigid and micro steps, some block artifacts are generated. I've confirmed these artifacts ARE present in the final transformed images (assuming they were generated).

After looking at the images, I'm guessing that data read/write using different pyramid / resolution levels is not properly updating regions that are outside of the tissue mask at the lower resolution level. I'm not sure if that's helpful, but I confess I didn't explore too deeply. I'll probably just omit the final micro-registration step and that should resolve the problem for my use case.

If I can test a solution for this, please let me know. Thanks again for your efforts!!
![rigid_registration](https://user-images.githubusercontent.com/12981489/210891812-aac518eb-1409-498e-80a8-3c48ddcf7c32.png)
![non-rigid_registration](https://user-images.githubusercontent.com/12981489/210891834-66f9e0b9-2640-43cb-bf5e-3df895293d5e.png)
![micro_registration](https://user-images.githubusercontent.com/12981489/210891848-63808d34-9543-4958-ad6f-8b286f9aa9f7.png)

**Comment by cdgatenbee** [comment]
Hi @NichD, apologies for the delayed response. This is indeed strange, I'll have to look into it. Would you happen to have any images you could share so that I could re-create the issue? 

Best,
-Chandler

**Comment by cdgatenbee** [comment]
Hi @NichD, that would be great if you can share the images and parameters. E-mail would work if the images are small enough, but if not maybe something like WeTransfer or Google Drive or Dropbox? Either way, my e-mail is Chandler.Gatenbee@moffitt.org

**Comment by NichD** [comment]
@cdgatenbee thank you for the update. These images are quite large, so I'll confirm how best to share and shoot you an email and comment here once I've set that up. Cheers!

**Comment by NichD** [comment]
Hi @cdgatenbee - Thanks for the update. I hadn't encountered this issue further since skipping the micro-reg step. Thanks for your help and efforts!

Cheers,

Nich
