### ISSUE TITLE
Issue in installing Valis-WSI

### ISSUE THREAD

**Issue by marco1108** [MathOnco/valis#34]
I am finding an error when trying to install valis-wsi on my Mac.

Python 3.11.0 | packaged by conda-forge | (main, Jan 15 2023, 05:44:48) [Clang 14.0.6 ]
Type "copyright", "credits" or "license" for more information.

IPython 8.8.0 -- An enhanced Interactive Python.

pip install valis-wsi
Collecting valis-wsi
  Using cached valis_wsi-1.0.0rc12-py3-none-any.whl (167 kB)
Requirement already satisfied: beautifulsoup4 in ./opt/anaconda3/envs/testapp/lib/python3.11/site-packages (from valis-wsi) (4.11.1)
Collecting bioformats-jar
  Using cached bioformats_jar-2020.5.27-py3-none-any.whl (10 kB)
Collecting scyjava
  Using cached scyjava-1.8.1-py3-none-any.whl (24 kB)
Requirement already satisfied: colorama in ./opt/anaconda3/envs/testapp/lib/python3.11/site-packages (from valis-wsi) (0.4.6)
Collecting colour-science
  Using cached colour_science-0.4.2-py3-none-any.whl (2.3 MB)
Collecting fastcluster
  Using cached fastcluster-1.2.6.tar.gz (173 kB)
  Installing build dependencies ... [?25ldone
etting requirements to build wheel ... [?25ldone
g metadata (pyproject.toml) ... [?25ldone
ollecting interpolation
  Using cached interpolation-2.2.1-py3-none-any.whl (56 kB)
Collecting joblib
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Collecting JPype1
  Using cached JPype1-1.4.1-cp311-cp311-macosx_10_9_universal2.whl (590 kB)
Collecting matplotlib
  Using cached matplotlib-3.6.3-cp311-cp311-macosx_10_12_x86_64.whl (7.3 MB)
Collecting numba
  Using cached numba-0.56.4.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... [?25lerror
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/n0/w0p7kny15zb2gs_2g1lw3ns80000gn/T/pip-install-eiw4ic9u/numba_3e4d3dd6c2b04a53905563a3cfb4266d/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/private/var/folders/n0/w0p7kny15zb2gs_2g1lw3ns80000gn/T/pip-install-eiw4ic9u/numba_3e4d3dd6c2b04a53905563a3cfb4266d/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.0; only versions >=3.7,<3.11 are supported.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
[?25hNote: you may need to restart the kernel to use updated packages.

**Comment by cdgatenbee** [comment]
Hi @marco1108,
Based on the error message, it looks like the issue is that you are using Python 3.11, but numba 0.56.4 (one of valis-wsi's required dependencies) doesn't support Python 3.11. Could you try creating a virtual environment that uses Python 3.10 and then try to re-install in that virtual environment? I will also be uploading a Docker Image for valis soon, so that will be another option in the very near future, and will help alleviate these dependencies issues. 

Best,
-Chandler

**Comment by marco1108** [comment]
Hi @cdgatenbee! Many thanks for prompt responce!

I have done a new anaconda space with Python 3.1. Now it gives me another issue:

OSError: cannot load library 'libvips.42.dylib': dlopen(libvips.42.dylib, 0x0002): tried: '/Users/marcopisa/opt/anaconda3/envs/valis/lib/python3.10/site-packages/../../libvips.42.dylib' (no such file), '/Users/marcopisa/opt/anaconda3/envs/valis/bin/../lib/libvips.42.dylib' (no such file), 'libvips.42.dylib' (no such file), '/usr/local/lib/libvips.42.dylib' (no such file), '/usr/lib/libvips.42.dylib' (no such file), '/Users/marcopisa/Downloads/libvips.42.dylib' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libvips.42.dylib'

Do you know how I could solve this?

Here below the full message:

pip install valis-wsi
Collecting valis-wsi
  Using cached valis_wsi-1.0.0rc12-py3-none-any.whl (167 kB)
Collecting tqdm
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting scyjava
  Using cached scyjava-1.8.1-py3-none-any.whl (24 kB)
Collecting Shapely
  Downloading shapely-2.0.0-cp310-cp310-macosx_10_9_x86_64.whl (1.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 8.0 MB/s eta 0:00:00
[?25hCollecting JPype1
  Downloading JPype1-1.4.1-cp310-cp310-macosx_10_9_universal2.whl (590 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 590.1/590.1 kB 6.3 MB/s eta 0:00:00
[?25hCollecting scikit-image
  Downloading scikit_image-0.19.3-cp310-cp310-macosx_10_13_x86_64.whl (13.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 21.2 MB/s eta 0:00:00
[?25hCollecting scikit-learn
  Downloading scikit_learn-1.2.1-cp310-cp310-macosx_10_9_x86_64.whl (9.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 20.0 MB/s eta 0:00:00
[?25hCollecting scipy
  Downloading scipy-1.10.0-cp310-cp310-macosx_10_15_x86_64.whl (35.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.1/35.1 MB 13.6 MB/s eta 0:00:00
[?25hCollecting joblib
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Collecting numba
  Downloading numba-0.56.4-cp310-cp310-macosx_10_14_x86_64.whl (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 14.7 MB/s eta 0:00:00
[?25hCollecting pandas
  Downloading pandas-1.5.3-cp310-cp310-macosx_10_9_x86_64.whl (12.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 17.7 MB/s eta 0:00:00
irement already satisfied: beautifulsoup4 in ./opt/anaconda3/envs/valis/lib/python3.10/site-packages (from valis-wsi) (4.11.1)
Collecting ome-types
  Using cached ome_types-0.3.2-py3-none-any.whl (142 kB)
Collecting SimpleITK
  Downloading SimpleITK-2.2.1-cp310-cp310-macosx_10_9_x86_64.whl (45.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 MB 4.8 MB/s eta 0:00:00
[?25hCollecting weightedstats
  Using cached weightedstats-0.4.1-py3-none-any.whl (3.8 kB)
Collecting interpolation
  Using cached interpolation-2.2.4-py3-none-any.whl (69 kB)
Collecting Pillow
  Downloading Pillow-9.4.0-2-cp310-cp310-macosx_10_10_x86_64.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 11.9 MB/s eta 0:00:00
[?25hCollecting fastcluster
  Downloading fastcluster-1.2.6-cp310-cp310-macosx_10_9_x86_64.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.1/40.1 kB 666.4 kB/s eta 0:00:00
[?25hCollecting numpy
  Downloading numpy-1.24.1-cp310-cp310-macosx_10_9_x86_64.whl (19.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.8/19.8 MB 16.9 MB/s eta 0:00:00
[?25hCollecting opencv-contrib-python
  Using cached opencv_contrib_python-4.7.0.68-cp37-abi3-macosx_10_13_x86_64.whl (61.3 MB)
Collecting bioformats-jar
  Using cached bioformats_jar-2020.5.27-py3-none-any.whl (10 kB)
Collecting pyvips
  Using cached pyvips-2.2.1.tar.gz (633 kB)
  Preparing metadata (setup.py) ... [?25ldone
ollecting matplotlib
  Downloading matplotlib-3.6.3-cp310-cp310-macosx_10_12_x86_64.whl (7.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 20.1 MB/s eta 0:00:00
[?25hRequirement already satisfied: colorama in ./opt/anaconda3/envs/valis/lib/python3.10/site-packages (from valis-wsi) (0.4.6)
Collecting colour-science
  Using cached colour_science-0.4.2-py3-none-any.whl (2.3 MB)
Requirement already satisfied: soupsieve>1.2 in ./opt/anaconda3/envs/valis/lib/python3.10/site-packages (from beautifulsoup4->valis-wsi) (2.3.2.post1)
Collecting imageio<3,>=2
  Using cached imageio-2.25.0-py3-none-any.whl (3.4 MB)
Requirement already satisfied: typing-extensions<5,>=4 in ./opt/anaconda3/envs/valis/lib/python3.10/site-packages (from colour-science->valis-wsi) (4.4.0)
Collecting packaging<22.0,>=21.3
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting tempita<0.6.0,>=0.5.2
  Using cached Tempita-0.5.2-py3-none-any.whl (12 kB)
Requirement already satisfied: setuptools in ./opt/anaconda3/envs/valis/lib/python3.10/site-packages (from numba->valis-wsi) (66.1.1)
Collecting llvmlite<0.40,>=0.39.0dev0
  Downloading llvmlite-0.39.1-cp310-cp310-macosx_10_9_x86_64.whl (25.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.5/25.5 MB 15.8 MB/s eta 0:00:00
[?25hCollecting numpy
  Downloading numpy-1.23.5-cp310-cp310-macosx_10_9_x86_64.whl (18.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.1/18.1 MB 20.2 MB/s eta 0:00:00
[?25hCollecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting contourpy>=1.0.1
  Downloading contourpy-1.0.7-cp310-cp310-macosx_10_9_x86_64.whl (244 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.2/244.2 kB 7.2 MB/s eta 0:00:00
irement already satisfied: python-dateutil>=2.7 in ./opt/anaconda3/envs/valis/lib/python3.10/site-packages (from matplotlib->valis-wsi) (2.8.2)
Collecting pyparsing>=2.2.1
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.38.0-py3-none-any.whl (965 kB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.4-cp310-cp310-macosx_10_9_x86_64.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 2.1 MB/s eta 0:00:00
[?25hCollecting xmlschema>=1.4.1
  Using cached xmlschema-2.1.1-py3-none-any.whl (354 kB)
Collecting lxml>=4.8.0
  Downloading lxml-4.9.2-cp310-cp310-macosx_10_15_x86_64.whl (4.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 22.6 MB/s eta 0:00:00
[?25hCollecting pydantic[email]>=1.0
  Downloading pydantic-1.10.4-cp310-cp310-macosx_10_9_x86_64.whl (2.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 20.1 MB/s eta 0:00:00
ollecting Pint>=0.15
  Using cached Pint-0.20.1-py3-none-any.whl (269 kB)
Requirement already satisfied: pytz>=2020.1 in ./opt/anaconda3/envs/valis/lib/python3.10/site-packages (from pandas->valis-wsi) (2022.7.1)
Requirement already satisfied: cffi>=1.0.0 in ./opt/anaconda3/envs/valis/lib/python3.10/site-packages (from pyvips->valis-wsi) (1.15.1)
Collecting tifffile>=2019.7.26
  Using cached tifffile-2023.1.23.1-py3-none-any.whl (214 kB)
Collecting networkx>=2.2
  Using cached networkx-3.0-py3-none-any.whl (2.0 MB)
Collecting PyWavelets>=1.1.1
  Downloading PyWavelets-1.4.1-cp310-cp310-macosx_10_13_x86_64.whl (4.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 21.0 MB/s eta 0:00:00
[?25hCollecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting jgo
  Using cached jgo-1.0.5-py3-none-any.whl (15 kB)
Requirement already satisfied: pycparser in ./opt/anaconda3/envs/valis/lib/python3.10/site-packages (from cffi>=1.0.0->pyvips->valis-wsi) (2.21)
Collecting email-validator>=1.0.3
  Using cached email_validator-1.3.1-py2.py3-none-any.whl (22 kB)
Requirement already satisfied: six>=1.5 in ./opt/anaconda3/envs/valis/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->valis-wsi) (1.16.0)
Collecting elementpath<4.0.0,>=3.0.0
  Using cached elementpath-3.0.2-py3-none-any.whl (189 kB)
Requirement already satisfied: psutil in ./opt/anaconda3/envs/valis/lib/python3.10/site-packages (from jgo->scyjava->valis-wsi) (5.9.4)
Requirement already satisfied: idna>=2.0.0 in ./opt/anaconda3/envs/valis/lib/python3.10/site-packages (from email-validator>=1.0.3->pydantic[email]>=1.0->ome-types->valis-wsi) (3.4)
Collecting dnspython>=1.15.0
  Using cached dnspython-2.3.0-py3-none-any.whl (283 kB)
Building wheels for collected packages: pyvips
  Building wheel for pyvips (setup.py) ... [?25ldone
reated wheel for pyvips: filename=pyvips-2.2.1-py2.py3-none-any.whl size=54179 sha256=dfab1017aae55a2be8167a70f78b2dbe4d294c1303e4c8eb79c44003bafed3dd
  Stored in directory: /Users/marcopisa/Library/Caches/pip/wheels/37/df/34/27e4b586f5f709b9339e67e559e2f8efba52cecbfbc800e3ad
Successfully built pyvips
Installing collected packages: weightedstats, tempita, SimpleITK, tqdm, threadpoolctl, pyparsing, pydantic, Pint, Pillow, numpy, networkx, lxml, llvmlite, kiwisolver, joblib, jgo, fonttools, elementpath, dnspython, cycler, xmlschema, tifffile, Shapely, scipy, PyWavelets, pyvips, pandas, packaging, opencv-contrib-python, numba, imageio, fastcluster, email-validator, contourpy, scikit-learn, scikit-image, matplotlib, JPype1, interpolation, colour-science, scyjava, ome-types, bioformats-jar, valis-wsi
  Attempting uninstall: packaging
    Found existing installation: packaging 23.0
    Uninstalling packaging-23.0:
      Successfully uninstalled packaging-23.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pytoolconfig 1.2.4 requires packaging>=22.0, but you have packaging 21.3 which is incompatible.
Successfully installed JPype1-1.4.1 Pillow-9.4.0 Pint-0.20.1 PyWavelets-1.4.1 Shapely-2.0.0 SimpleITK-2.2.1 bioformats-jar-2020.5.27 colour-science-0.4.2 contourpy-1.0.7 cycler-0.11.0 dnspython-2.3.0 elementpath-3.0.2 email-validator-1.3.1 fastcluster-1.2.6 fonttools-4.38.0 imageio-2.25.0 interpolation-2.2.4 jgo-1.0.5 joblib-1.2.0 kiwisolver-1.4.4 llvmlite-0.39.1 lxml-4.9.2 matplotlib-3.6.3 networkx-3.0 numba-0.56.4 numpy-1.23.5 ome-types-0.3.2 opencv-contrib-python-4.7.0.68 packaging-21.3 pandas-1.5.3 pydantic-1.10.4 pyparsing-3.0.9 pyvips-2.2.1 scikit-image-0.19.3 scikit-learn-1.2.1 scipy-1.10.0 scyjava-1.8.1 tempita-0.5.2 threadpoolctl-3.1.0 tifffile-2023.1.23.1 tqdm-4.64.1 valis-wsi-1.0.0rc12 weightedstats-0.4.1 xmlschema-2.1.1
Note: you may need to restart the kernel to use updated packages.

runfile('/Users/marcopisa/Downloads/Script_Marco.py', wdir='/Users/marcopisa/Downloads')
Traceback (most recent call last):

  File ~/opt/anaconda3/envs/valis/lib/python3.10/site-packages/pyvips/__init__.py:19
    import _libvips

ModuleNotFoundError: No module named '_libvips'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File ~/opt/anaconda3/envs/valis/lib/python3.10/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/Downloads/Script_Marco.py:12
    from valis import preprocessing

  File ~/opt/anaconda3/envs/valis/lib/python3.10/site-packages/valis/__init__.py:3
    from . import affine_optimizer

  File ~/opt/anaconda3/envs/valis/lib/python3.10/site-packages/valis/affine_optimizer.py:22
    from . warp_tools import get_affine_transformation_params, \

  File ~/opt/anaconda3/envs/valis/lib/python3.10/site-packages/valis/warp_tools.py:17
    import pyvips

  File ~/opt/anaconda3/envs/valis/lib/python3.10/site-packages/pyvips/__init__.py:71
    vips_lib = ffi.dlopen(_vips_libname)

  File ~/opt/anaconda3/envs/valis/lib/python3.10/site-packages/cffi/api.py:150 in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)

  File ~/opt/anaconda3/envs/valis/lib/python3.10/site-packages/cffi/api.py:832 in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)

  File ~/opt/anaconda3/envs/valis/lib/python3.10/site-packages/cffi/api.py:827 in _load_backend_lib
    raise OSError(msg)

OSError: cannot load library 'libvips.42.dylib': dlopen(libvips.42.dylib, 0x0002): tried: '/Users/marcopisa/opt/anaconda3/envs/valis/lib/python3.10/site-packages/../../libvips.42.dylib' (no such file), '/Users/marcopisa/opt/anaconda3/envs/valis/bin/../lib/libvips.42.dylib' (no such file), 'libvips.42.dylib' (no such file), '/usr/local/lib/libvips.42.dylib' (no such file), '/usr/lib/libvips.42.dylib' (no such file), '/Users/marcopisa/Downloads/libvips.42.dylib' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libvips.42.dylib'

**Comment by cdgatenbee** [comment]
Hi @marco1108,
It looks like libvips hasn't been installed yet. Pleas try installing pyvips with `conda install -c conda-forge pyvips` and then pip installing valis-wsi. This should install both pyvips and libvips. If you still get the same error, maybe try installing libvips specifically with `conda install -c conda-forge libvips`. 

Best,
-Chandler

**Comment by marco1108** [comment]
Hi Chandler! Many thanks again! I have done as you suggested and it installed it. Unfortunately I got another issue when running valis:

ExecutableNotFound: mvn not found on path /Users/marcopisa/opt/anaconda3/envs/valis/bin:/Users/marcopisa/opt/anaconda3/condabin:/bin:/Users/marcopisa/opt/anaconda3/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/anaconda2/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/opt/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Many many thanks for your support

**Comment by cdgatenbee** [comment]
Hi @marco1108,
So sorry about these installation troubles. This one is because one of the dependencies, scyjava, requires that Maven be installed (in order to get the Bio-formats jar file). It's a recent change, and I'd forgotten to update the README with these additional installation requirements, but will do so soon. Anyhow, you should be able to install Maven via conda with `conda install -c conda-forge maven`. Please try that and let me know how it goes.

Best,
-Chandler

**Comment by cdgatenbee** [comment]
Hi @marco1108, so sorry again. I _think_ the issue is that because you're in an anaconda environment, it's looking for Java there. Since valis is being installed with pip, pip is installing [JPype](https://pypi.org/project/JPype1/), but not the JDK. However, to get around this, maybe uninstall JPype (`pip uninstall JPype1`), and then reinstall with conda (`conda install -c conda-forge jpype1`). This should install both JPype and the JDK. At some point I'd also like to valis-wsi on conda-forge to avoid these pip/conda issues.

Best,
-Chandler

**Comment by marco1108** [comment]
Hi Chandler. Apologies for bothering again, but still some issues with JAVA. 

JVMNotFoundException: No JVM shared library file (libjli.dylib) found. Try setting up the JAVA_HOME environment variable properly.

I confirm that I am using an anaconda space, should I use a different space?

Many thanks

**Comment by marco1108** [comment]
I have tried I have tried to install Java thorugh “conda install -c bioconda java-jdk”, but it did not work I fear.
 
“Collecting package metadata (current_repodata.json): done
Solving environment: /
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:
 
  - conda-forge/noarch::nbconvert-core==7.2.9=pyhd8ed1ab_0
  - conda-forge/noarch::qtconsole==5.4.0=pyhd8ed1ab_0
  - conda-forge/noarch::rope==1.6.0=pyhd8ed1ab_0
  - conda-forge/noarch::qtawesome==1.2.2=pyhd8ed1ab_0
  - conda-forge/noarch::bleach==6.0.0=pyhd8ed1ab_0
  - conda-forge/noarch::pytoolconfig==1.2.4=pyhd8ed1ab_1
  - conda-forge/osx-64::pyqtwebengine==5.15.7=py310hdd03f62_2
  - conda-forge/noarch::nbconvert-pandoc==7.2.9=pyhd8ed1ab_0
  - conda-forge/noarch::ipykernel==6.20.2=pyh736e0ef_0
  - conda-forge/noarch::python-lsp-server==1.7.1=hd8ed1ab_0
  - conda-forge/noarch::nbconvert==7.2.9=pyhd8ed1ab_0
  - conda-forge/noarch::qdarkstyle==3.0.3=pyhd8ed1ab_0
  - conda-forge/osx-64::sip==6.7.5=py310h7a76584_0
  - conda-forge/noarch::python-lsp-black==1.2.1=pyhd8ed1ab_0
  - conda-forge/noarch::sphinx==6.1.3=pyhd8ed1ab_0
  - conda-forge/noarch::qtconsole-base==5.4.0=pyha770c72_0
  - conda-forge/noarch::spyder-kernels==2.4.2=unix_pyhd8ed1ab_0
  - conda-forge/noarch::numpydoc==1.5.0=pyhd8ed1ab_0
  - conda-forge/osx-64::spyder==5.4.2=py310h2ec42d9_0
  - conda-forge/noarch::pyls-spyder==0.4.0=pyhd8ed1ab_0
  - conda-forge/osx-64::pyqt==5.15.7=py310hdd03f62_2
  - conda-forge/noarch::qtpy==2.3.0=pyhd8ed1ab_0
  - conda-forge/osx-64::pyqt5-sip==12.11.0=py310h415000c_2
  - conda-forge/osx-64::jpype1==1.4.1=py310ha23aa8a_1
done
 
## Package Plan ##
 
  environment location: /Users/marcopisa/opt/anaconda3/envs/valis
 
  added / updated specs:
    - java-jdk
 
 
The following packages will be downloaded:
 
    package                    |            build
    ---------------------------|-----------------
    java-jdk-7.0.91            |                1        34.0 MB  bioconda
    ------------------------------------------------------------
                                           Total:        34.0 MB
 
The following NEW packages will be INSTALLED:
 
  java-jdk           bioconda/osx-64::java-jdk-7.0.91-1
  packaging          conda-forge/noarch::packaging-23.0-pyhd8ed1ab_0
 
 
 
Downloading and Extracting Packages
                                                                               
Preparing transaction: done
Verifying transaction: \ WARNING conda.core.path_actions:verify(1094): Unable to create environments file. Path not writable.
  environment location: /Users/marcopisa/.conda/environments.txt
 
done
Executing transaction: \ WARNING conda.core.envs_manager:register_env(49): Unable to register environment. Path not writable or missing.
  environment location: /Users/marcopisa/opt/anaconda3/envs/valis
  registry file: /Users/marcopisa/.conda/environments.txt
done
 
Note: you may need to restart the kernel to use updated packages.”

**Comment by cdgatenbee** [comment]
Hi @marco1108, 
Were you able to successfully install everything? If not, there is now a Docker Image you can download from docker hub that has everything you need to run valis. You can find it here: https://hub.docker.com/r/cdgatenbee/valis-wsi . Sorry I couldn't be of more help getting Java setup, but hopefully the Docker Image will be of use.

Best,
-Chandler

**Comment by syy-create** [comment]
> Hi Chandler. Apologies for bothering again, but still some issues with JAVA.
> 
> JVMNotFoundException: No JVM shared library file (libjli.dylib) found. Try setting up the JAVA_HOME environment variable properly.
> 
> I confirm that I am using an anaconda space, should I use a different space?
> 
> Many thanks

May I ask how you finally solved this problem? I also encountered the same error message
