### ISSUE TITLE
`match_desc_and_kp` possibly missing `max_ratio` argument

### ISSUE THREAD

**Issue by idc9** [MathOnco/valis#36]
Should `match_desc_and_kp` include `max_ratio` as an argument and pass it to `match_descriptors`  in [this line](https://github.com/MathOnco/valis/blob/23def05869af12ba31d8f3dca60ed0302fb1c3b0/valis/feature_matcher.py#L543)?

**Comment by cdgatenbee** [comment]
Hi @idc9,
Thanks for pointing this out. I've added it as an argument, and the updated function will be part of the next release (1.0.0rc14).

Best,
-Chandler
