### ISSUE TITLE
keyword "max_non_rigid_registartion_dim_px" misspelled

### ISSUE THREAD

**Issue by zindy** [MathOnco/valis#39]
Hello,

would it be OK if I sent you a PR changing `max_non_rigid_registartion_dim_px` into `max_non_rigid_registration_dim_px` ?

See the files that would be affected by the change: https://github.com/MathOnco/valis/search?q=registartion

Cheers,
Egor

**Comment by cdgatenbee** [comment]
Hi @zindy,
Ooops, thanks for pointing out typo! I have an approach I'd like to use that can treat the misspelled keyword like a deprecated argument, and it would avoid inducing argument errors in anyone's existing scripts. I'll have it fixed the next update. 

Best,
-Chandler
