### ISSUE TITLE
Mask generation failing on select sub-tiles

### ISSUE THREAD

**Issue by NichD** [MathOnco/valis#44]
Hi @cdgatenbee - I encountered a corner case that is causing VALIS to fail in the early registration steps, where tissue masks are being generated per-tile. The error occurs at line 531 of `preprocessing.py`, in the `create_tissue_mask_from_rgb` method.

I believe what is happening is that a tile is being created that is an entirely background / no-value ROI. As such, all pixels are single-valued (0 in the case of a no-value ROI). That is causing the `skimage.filters.threshold_multiotsu` method to fail as it cannot generate a threshold from a single-valued histogram.

I modified the `create_tissue_mask_from_rgb` method to handle the case of an empty mask, but that created downstream issues presumably tied to passing around empty images for denoising, feature detection, etc. I expect I've overlooked a step where we omit empty tiles from downstream processing. I'm happy to test and debug something if helpful.

**Comment by cdgatenbee** [comment]
Hi @NichD, thanks for pointing this out! It does seem like there should be a way to "ignore" what are essentially blank, featureless images. Maybe I can just do an early check to see if they're empty, and if they are assign them identity transforms and skip them for the remainder of the pipeline? Will need to test if this is a workable solution though. I'll add it to the "to-do" list :) 

-Chandler

**Comment by NichD** [comment]
Hi @Cgatenbee - That's basically the solution that I was imagining as I
explored that problem. If there's something I can help with in regards to
this problem, please let me know!

- Nich

Nicholas Dana, PhD
(801) 856-4129
***@***.***

**Comment by NichD** [comment]
Hi @cdgatenbee - I wanted to follow up regarding this and see if you have any thoughts or suggestions. I've been encountering this error more frequently. Based on my previous comments about encountering an empty background ROI, I've attempted to side-step this issue by changing the `max_image_dim_px` parameter, in an attempt to widen the FOV and minimize this chance. Somehow, whatever value I input is always overwritten with 512, regardless of the value or image (`UserWarning: Smallest image is less than max_image_dim_px. parameter max_image_dim_px is being set to 512`). I may attempt a hacky work around to address this, but any suggestions you have are welcome.

Best,

Nich

**Comment by cdgatenbee** [comment]
Hi @NichD,
I just pushed the most recent update (1.0.0rc14) which now skips empty images and should hopefully avoid these errors. Please try it out and let me know if it resolves this issue. 

Best,
-Chandler

**Comment by NichD** [comment]
Hi @cdgatenbee - That's great, thank you for the effort!

Unfortunately, I tried testing it out and I think I'm the victim of another issue. Our slide images are CZI files and I noted on the changelog an update to the reader associated with CZI files. I suspect that update inadvertently broke how the CZI files are being imported for me.

I have some experience in Python related to importing CZI files. I'm going to explore the slide readers and see if I can't suggest some edits. Much appreciated!

**Comment by NichD** [comment]
@cdgatenbee - Apologies again for repeat messages. I've found the new error I encountered may be a result of an import issue? on `slide_io.py`, line 2338, we're checking file extensions and trying to use CziFile - but I'm not seeing it imported anywhere. Adding `from aicspylibczi import CziFile` to line 29 resolved my issue.

**Comment by cdgatenbee** [comment]
Hi @NichD,
Sorry about the issue :( I don't recall the exact error, but for some reason poetry can't install aicspylibczi (even though it is installable via pip), and so I had added a warning message that aicspylibczi needs to be installed if valis uses the `CziJpgxrReader` and aicspylibczi isn't installed. However, what I had forgotten is that the message will probably get hidden most of the time :( So, I'll have to either figure out how to get poetry to install aicspylibczi, or move the warning message. I'll also check out  pylibCZIrw as an alternative to aicspylibczi. However, if you would like to use the Bioformats reader (which is what was being used before), you should be able set  `reader_cls=slide_io.BioFormatsSlideReader` when you call `Valis.register`. Sorry again for this issue, it's kind of a silly error that I'll fix asap.

Best,
-Chandler

**Comment by cdgatenbee** [comment]
Hi @NichD, 
I think I've fixed the original issue and the ```aicspylibczi``` import issue, so I'm going to go ahead and close this issue.

Best,
-Chandler

**Comment by NichD** [comment]
Hi @cdgatenbee - Understood, thanks for the update. I'll make sure to pull the latest and reach out with any updates. Thanks for your hard work!!
