### ISSUE TITLE
aligning two H&E files

### ISSUE THREAD

**Issue by GlastonburyC** [MathOnco/valis#48]
I have two H&E brightfield ome-tiffs one that's faded and one thats restained that I would like to register.

However, the results come out "pink" see attached. Is there any solution to this, as it renders the outputted registered tiff unusable.

<img width="496" alt="Screenshot 2023-04-25 at 23 18 44" src="https://user-images.githubusercontent.com/4210507/234406617-9d873352-5fac-43ac-bf20-c163b6a1339a.png">

**Comment by cdgatenbee** [comment]
Hi @GlastonburyC, 
I noticed the issue was closed pretty quickly. Were you able to resolve the issue? If so, what was the solution? If not, do you think it is similar to [issue 26](https://github.com/MathOnco/valis/issues/26)? 

Best,
-Chandler
