### ISSUE TITLE
Local variable 'is_flattended_pyramid' referenced before assignment

### ISSUE THREAD

**Issue by Jose-Verdu-Diaz** [MathOnco/valis#5]
On `valis > slide_io.py > check_flattened_pyramid_tiff()` , in `line 434`

Variable `is_flattended_pyramid` is not initialized to False, producing an error with some ome.tiff filetypes.

**Comment by Jose-Verdu-Diaz** [comment]
#6

**Comment by cdgatenbee** [comment]
Thanks for bringing this to my attention! I've added the fix in version 1.0.0rc6
