### ISSUE TITLE
micro registration failing

### ISSUE THREAD

**Issue by GlastonburyC** [MathOnco/valis#50]
I am trying to register a WSI to a reference WSI.

```
import registration
slide_src_dir = "/Users/craig.glastonbury/Projects/ome_tiff/"
results_dst_dir = "./slide_registration_example"
reference_slide = "case01_post.ndpi"
registered_slide_dst_dir = "./slide_registration_example/registered_slides"
registrar = registration.Valis(slide_src_dir,
                                results_dst_dir,
                                reference_img_f=reference_slide,
                                align_to_reference=True,
                                max_processed_image_dim_px=8000,
                                max_image_dim_px=8000,
                                thumbnail_size=8000)
rigid_registrar, non_rigid_registrar, error_df = registrar.register()
registrar.register_micro(max_non_rigid_registartion_dim_px=2000, 
                         align_to_reference=True, 
                         tile_wh=256, 
                         reference_img_f=reference_slide
                         )
registrar.warp_and_save_slides(registered_slide_dst_dir, crop="reference")
registration.kill_jvm()
```

If I comment out `register_micro` everything works. But I really need to improve the registration, as when I take corresponding tiles from each image, they are still badly registered.

I get the following error:

```
==== Performing microregistration

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:07<00:00,  3.61s/it]

======== Non-rigid registration complete in 7.645 seconds

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/craig.glastonbury/valis/valis/registration.py", line 3793, in register_micro
    updated_bk_dxdy = current_bk_dxdy + new_bk_dxdy
  File "/Users/craig.glastonbury/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pyvips/vimage.py", line 1494, in __add__
    return self.linear(1, other)
  File "/Users/craig.glastonbury/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pyvips/vimage.py", line 1347, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File "/Users/craig.glastonbury/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pyvips/voperation.py", line 282, in call
    op.set(name, intro.details[name]['flags'], match_image, value)
  File "/Users/craig.glastonbury/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pyvips/voperation.py", line 216, in set
    super(Operation, self).set(name, value)
  File "/Users/craig.glastonbury/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pyvips/vobject.py", line 122, in set
    gv.set(value)
  File "/Users/craig.glastonbury/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pyvips/gvalue.py", line 193, in set
    array = ffi.new('double[]', value)
  File "/Users/craig.glastonbury/.pyenv/versions/3.10.2/lib/python3.10/site-packages/cffi/api.py", line 267, in new
    return self._backend.newp(cdecl, init)
TypeError: expected new array length or list/tuple/str, not numpy.ndarray
```

**Comment by cdgatenbee** [comment]
Hi @GlastonburyC, 
I _think_ this error might be related to the original non-rigid registration probably producing `pyvips.Image` objects (because they are probably fairly large in this example), but valis assuming they would be numpy arrays (produced when non-rigid registration is on smaller images, the default behavior). I believe I've fixed this issue, which will be in the next update, which will be pushed very soon.  Anyhow, in the meantime, have you tried running this using the default parameters? One reason for the poor registration might be that `max_processed_image_dim_px=8000`, which determines the size of the image used for rigid registration. I've personally found that using large images for the rigid registration tends to produce very poor results, so if you haven't done it already, I'd suggest to try reducing that value (default is 850). To improve the alignment of the smaller details using higher resolution images, you can conduct the micro-registration with the larger image sizes. Also, while I admit I haven't experimented that much with the tile size during micro-registration, 256 might be on the small size, and I don't think there will be much of a benefit to using smaller tiles. So, the code would look like:

```
import registration
slide_src_dir = "/Users/craig.glastonbury/Projects/ome_tiff/"
results_dst_dir = "./slide_registration_example"
reference_slide = "case01_post.ndpi"
registered_slide_dst_dir = "./slide_registration_example/registered_slides"
registrar = registration.Valis(slide_src_dir,
                                results_dst_dir,
                                reference_img_f=reference_slide,
                                align_to_reference=True)
rigid_registrar, non_rigid_registrar, error_df = registrar.register()
registrar.register_micro(max_non_rigid_registartion_dim_px=8000, 
                         align_to_reference=True, 
                         reference_img_f=reference_slide
                         )
registrar.warp_and_save_slides(registered_slide_dst_dir, crop="reference")
registration.kill_jvm()

``` 

Again, I apologize for the error, but should hopefully have that fix available soon. Please let me know if the above code works for you, though.

Best,
-Chandler

**Comment by GlastonburyC** [comment]
Hey Chandler,

No need to apologise, I really appreciate your detailed response. I tried the code you provided and it totally works. However, the registration is still poor. I've attached an example. It's warped too much (perhaps I only need rigid registration) but also displaced too, as you can see from this GIF of original and registered:
![ezgif-2-ec0fa9e7de](https://user-images.githubusercontent.com/4210507/236570444-052fe618-aa6e-4cf0-b488-82c0bde38617.gif)

**Comment by GlastonburyC** [comment]
Here is the result wit rigid only... Any further fine-tuning advice would be appreciated as for my downstream use-case I need them to be as close as possible on a patch by patch basis.
> <img src="https://user-images.githubusercontent.com/4210507/236627377-250b666a-9cc4-425c-a6a9-5cba2d8762f9.gif" width="256" height="256" alt="ezgif-2-389cdc3d53">

**Comment by cdgatenbee** [comment]
Hi @GlastonburyC ,
Glad the code ended up working out. I think there may be a few things that could be done to possibly improve the aligments. First, @aelskens added an Image Processor that will perform [H&E deconvolution](https://valis.readthedocs.io/en/latest/preprocessing.html#valis.preprocessing.HEDeconvolution), which may be more suitable if all of your images are H&E. To use it, pass the uninstantiated class as an argument to the registration method, i.e. 

```
registrar.register(brightfield_processing_cls=preprocessing.HEDeconvolution, brightfield_processing_kwargs={})
```
Also, I believe I've fixed the initial issue, and so you could also try setting ```max_non_rigid_registartion_dim_px=8000```  when you initialize the ```Valis``` object, and then probably skip the micro-registration (unless you'd like to use even larger images). If the non-rigid registration still ends up deforming the images too much, it would also be possible to do the initial rigid registration as you have above, and then save each set of patches that need to be refined. You could then run valis on each set of patches (again using only the rigid registration) to get the patches aligned as closely as possible. Maybe not ideal, but if it's a patch analysis maybe it will be ok, as it should align the patches and avoid non-rigid deformations. If you'd like to take this approach and run into any issues or have questions, let me know and maybe I could help.

Best,
-Chandler

**Comment by GlastonburyC** [comment]
When I try this on a single pair of patches moved to a directory it all works (I can see all the results: masks, rigid registrations, non-rigidregistration thumbails etc) but the tiff outputted by `registrar.warp_and_save_slides` are completely black?

**Comment by cdgatenbee** [comment]
Hi @GlastonburyC, 
Glad to hear the tile registration is (mostly) working out so far. To register only subsets of images, you can pass the specific file names to the ```img_list``` argument when you initialize your ```Valis``` object. So, you could loop through your files and pass in only the image pairs you want to register, i.e. something like:

```
from valis import valtils
pre_tiles  = os.listdir("case01/pre/")
post_tiles = os.listdir("case01/post/")
valtils.sort_nicely(pre_tiles)
valtils.sort_nicely(post_tiles)

for i in range(len(pre_tiles)):
    registrar = registration.Valis("/Users/craig.glastonbury/Projects/case01/pre/",
                                results_dst_dir,
                                img_list = [os.path.join("case01/pre", pre_tiles[i]), os.path.join("case01/post", post_tiles[i])],
                                reference_img_f=pre_tiles[i],
                                name=str(i),
                                align_to_reference=True,
                                max_non_rigid_registration_dim_px=1024,
                                thumbnail_size=1024)
                                
    rigid_registrar, non_rigid_registrar, error_df = registrar.register(brightfield_processing_cls=preprocessing.HEDeconvolution, brightfield_processing_kwargs={})

```

Regarding the output tiff being empty, would you be willing to share the 2 images you are trying to register? I could then use those to figure out why the output is completely black.

Best,
-Chandler

**Comment by GlastonburyC** [comment]
Sure @cdgatenbee - What is your email?

**Comment by cdgatenbee** [comment]
you can send them to Chandler.Gatenbee@moffitt.org

**Comment by cdgatenbee** [comment]
Closing, as we were able to resolve the issue over e-mail. The following code seems to have worked well for registering pairs of tiles where sometimes the H&E staining was unusual: 

```
registrar = registration.Valis(src_dir, dst_dir,
                               align_to_reference=True,
                               max_non_rigid_registration_dim_px=1024,
                               thumbnail_size=1024,
                               create_masks=False)


rigid_registrar, non_rigid_registrar, error_df = registrar.register()
```

**Comment by syy-create** [comment]
> Thanks @cdgatenbee. I tested out the following:
> 
> ```
> registrar = registration.Valis("/Users/craig.glastonbury/Projects/case01/pre/",
>                                 results_dst_dir,
>                                 reference_img_f=pre_tiles[0],
>                                 align_to_reference=True,
>                                 max_non_rigid_registration_dim_px=1024,
>                                 thumbnail_size=1024)
>                                 
> rigid_registrar, non_rigid_registrar, error_df = registrar.register(brightfield_processing_cls=preprocessing.HEDeconvolution, brightfield_processing_kwargs={})
> ```
> 
> This worked really well!
> 
> However.. For my use case, I will have lets say 1000 patches in "case01/pre" and 1000 patches in "case01/post". Each will be called tile1.png, tile2.png... etc.
> 
> I would like to have `case01/pre/tile1.png` as a reference "slide" and `case01/post/tile1.png` as the slide to register. Then I would like to have `case01/pre/tile2.png` as reference, and `case01/post/tile2.png` to register... and so on.
> 
> Its not exactly clear to me how I can achieve this efficiently with Valis? Any pointers would be immensely helpful.

Hi @GlastonburyC ,
Hello, I would like to ask if the 1000 patches you have divided here are dividing a whole slide into 1000 patches, or is it just batch registration of patches, not the same slide.
