### ISSUE TITLE
readthedocs: image_type  class init:  img_type

### ISSUE THREAD

**Issue by Gibbsdavidl** [MathOnco/valis#54]
In the readthedocs: "image_type" but in the class init:  "img_type".

**Comment by cdgatenbee** [comment]
Hi @Gibbsdavidl, 
Thanks for pointing out that the input argument is in ```Valis.__init__``` is ```img_type```, but the attribute is actually ```image_type```. In the next update, the argument in ```Valis.__init__``` will be changed from ```img_type``` to ```image_type```. However,  ```img_type``` will still work so as to maintain backwards compatibility. 

Best,
-Chandler
