### ISSUE TITLE
Error running basic example 

### ISSUE THREAD

**Issue by cwenge** [MathOnco/valis#7]
Hey there, 

I tried setting up your tool in a Docker container and running the basic example listed in the README. Unfortunately, I get the following error when initializing the Valis Class:
`AttributeError: module 'bioformats_jar' has no attribute 'start_jvm'`

Is this a known Error? This might be due to different versions of libraries or OS...? I've tried with Ubuntu 22.04 (Python 10) and Ubuntu 20.04 (Python 3.8) and also OpenJDK18 and OpenJDK8. Can you please tell me which setup/environment you had for successfully running VALIS?

Here is also the output of pip list:

Package               Version\
--------------------- ----------- \
beautifulsoup4        4.11.1      \
bioformats-jar        2020.5.27   \
cffi                  1.15.0      \
colorama              0.4.5       \
colour-science        0.4.1       \
cycler                0.11.0      \
dbus-python           1.2.16      \
dnspython             2.2.1       \
elementpath           2.5.3       \
email-validator       1.2.1       \
fastcluster           1.2.6       \
fonttools             4.33.3      \
idna                  3.3         \
imageio               2.19.3      \
interpolation         2.2.1       \
jgo                   1.0.4       \
joblib                1.1.0       \
JPype1                1.4.0       \
kiwisolver            1.4.3       \
llvmlite              0.38.1      \
lxml                  4.9.0       \
matplotlib            3.5.2       \
networkx              2.8.4       \
numba                 0.55.2      \
numpy                 1.22.0      \
ome-types             0.3.0       \
opencv-contrib-python 4.6.0.66    \
packaging             21.3        \
pandas                1.4.3       \
Pillow                9.1.1       \
Pint                  0.19.2      \
pip                   20.0.2      \
psutil                5.9.1       \
pycparser             2.21        \
pydantic              1.9.1       \
PyGObject             3.36.0      \
pyparsing             3.0.9       \
python-dateutil       2.8.2       \
pytz                  2022.1      \
pyvips                2.2.1       \
PyWavelets            1.3.0       \
scikit-image          0.19.3      \
scikit-learn          1.1.1       \
scipy                 1.8.1       \
scyjava               1.5.1       \
setuptools            45.2.0      \
Shapely               1.8.2       \
SimpleITK             2.1.1.2     \
six                   1.16.0      \
soupsieve             2.3.2.post1 \
Tempita               0.5.2       \
threadpoolctl         3.1.0       \
tifffile              2022.5.4    \
tqdm                  4.64.0      \
typing-extensions     4.2.0       \
valis-wsi             1.0.0rc6    \
weightedstats         0.4.1       \
wheel                 0.34.2      \
xmlschema             1.11.3 \

Any suggestions are highly welcomed. Thanks :)

**Comment by cdgatenbee** [comment]
Hello,
Thanks for bringing this to my attention. It looks like bio-formats has been deprecated in favor of scyjava, and in this last version they removed the start_jvm() function. I'll update the code to use scyjava and push it asap.

Best
-Chandler

**Comment by cdgatenbee** [comment]
Hello @cwenge ,
I've updated the code to use scyjava instead of bio-formats, which I think will fix this issue. If not, please let me know. 

Best,
-Chandler

**Comment by cwenge** [comment]
> Hello @cwenge , I've updated the code to use scyjava instead of bio-formats, which I think will fix this issue. If not, please let me know.
> 
> Best, -Chandler

Hey @cdgatenbee,
thanks, it works now! If there is interest, I can provide a simple set up Dockerfile so other users can quickly try out your tool. I could post it tomorrow.

Best regards, 

Chris

**Comment by cwenge** [comment]
This is the Dockerfile I currently use to test your tool:

```
FROM ubuntu:22.04

# set timezone to avoid get prompted for configuration while installing openjdk8
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update && apt install -y \
	curl \
        wget \
        build-essential \
        git \
        openjdk-8-jdk \
        gcc \
        make \
        cmake \
	maven \
        python3-pip\
    && apt clean \
    && rm -rf /var/lib/apt/lists/*    

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV PATH="$PATH:$JAVA_HOME/bin"

# install pixman
RUN wget https://www.cairographics.org/releases/pixman-0.40.0.tar.gz -P /opt/
RUN tar -xf /opt/pixman-0.40.0.tar.gz --directory /opt/ \
    && rm /opt/pixman-0.40.0.tar.gz
WORKDIR /opt/pixman-0.40.0
RUN ./configure
RUN make \
    && make install \
    && make clean

RUN apt update && apt install -y \
    openslide-tools \
    libvips

RUN pip3 install pyvips valis-wsi numpy==1.22
```

It's sufficient for first trials. Unfortunately, I can't make SimpleElastix to install without errors in this set-up. I'll update the Dockerfile when I have time for it.

**Comment by cdgatenbee** [comment]
Thanks @cwenge , this is great! I'd like to test it out but I can add this as an installation option to the readme soon.
