### ISSUE TITLE
Non-monotonically increasing image values cause error in normalization

### ISSUE THREAD

**Issue by NichD** [MathOnco/valis#71]
Greetings Chandler (@cdgatenbee),

I encountered a corner-case when processing a histology stack recently. It occurred in the image normalization step, prior to registration. The error was thrown from [scipy.interpolate.Akima1DInterpolator](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.Akima1DInterpolator.html) as it was not recognizing the values in `src_stats_flat` as being strictly monotonic.

I see at line [892 in preprocessing.py](https://github.com/MathOnco/valis/blob/f5fa4a6383f27ff3a76014ab26513868dbc3e048/valis/preprocessing.py#L892) that you enforce monotonicity by applying an epsilon factor. I'm unclear why, but an epsilon of 10x-float-resolution did not seem sufficient to enforce monotonicity, but applying a 100x-float-resolution factor was sufficient to satisfy the monotonicity condition in `Akima1DInterpolator`.

I'll submit a pull request to implement this solution. Please let me know if you have any concerns and thanks for your hard work!

Regards,

Nicholas Dana (@nichd)

**Comment by NichD** [comment]
Update: [Pull request link](https://github.com/MathOnco/valis/pull/72)

**Comment by cdgatenbee** [comment]
Hi @NichD,
Thanks for fixing this and submitting the pull request! It's been merged into main and is in the most recent update from earlier this week. 

Best,
-Chandler
