### ISSUE TITLE
after registration, parameters for rigid registration 

### ISSUE THREAD

**Issue by WXY-Belief** [MathOnco/valis#73]
Hello, I would like to ask about how to obtain parameters for rigid registration, such as rotation angle and translation distance, after registration.

**Comment by WXY-Belief** [comment]
Thank you for your response.It's been a great help to me.

**Comment by WXY-Belief** [comment]
Thank you for your response. It's a great help to me.

**Comment by cdgatenbee** [comment]
Great! I'll go ahead and close the issue then.

Best,
-Chandler
