### ISSUE TITLE
non-rigid registration

### ISSUE THREAD

**Issue by cristinaperez9** [MathOnco/valis#79]
What is the non-rigid registration method (e.g. Deep Flow, SimpleElastix or Groupwise SimpleElastix) that is used when executing the following lines?

registrar = registration.Valis(slide_src_dir, results_dst_dir)
rigid_registrar, non_rigid_registrar, error_df = registrar.register()

I found these lines in one of the examples that are provided in: https://valis.readthedocs.io/en/latest/examples.html

Thank you in advance!

**Comment by cdgatenbee** [comment]
Hi @cristinaperez9,
Sorry for taking so long to respond, but Deep Flow is used as the default non-rigid registration method, and so is what would be used in those examples. I hope that answers your question, but if you'd like some more info please let me know.

Best,
-Chandler
