### ISSUE TITLE
Saving as SVS file?

### ISSUE THREAD

**Issue by ciaobladoo** [MathOnco/valis#88]
Thank you for your good work. We have achieved excellent registration results with Valis. I wanted to ask: could the registered images be saved as SVS format instead of ome.tiff? Thanks!

**Comment by cdgatenbee** [comment]
Hi @ciaobladoo, 

So happy to hear that you're getting good results with Valis! Valis uses libvips to write the images, which unfortunately means it does not support writing SVS images. However, while the built in functions write an ome.tiff, it would be possible to write any format supported by libvips (TIFF, JPEG (JFIF), PPM/PGM/PBM/PFM, PNG, CSV, EXR, HDR (Radiance), Matlab, FITS, webp, Openslide and VIPS file formats, see the [docs](https://github.com/libvips/libvips/wiki/Libvips) for more info). If one of those formats would be preferable, let me know and I could put together some example code on how to save in one of those formats. Also, if you don't mind my asking, are there any particular reasons that you'd prefer SVS (or some other format) over ome.tiff? Just wondering if there are issues with ome.tiff that I may not be aware of.

Best,
-Chandler

**Comment by ciaobladoo** [comment]
Hey Chandler,

Thank you for the swift response. I wanted '.svs' format because I thought some of my code for tiling WSI doesn't work for ome.tiff. But I tried today and it works. Not sure what was going on before but I no longer need help at the moment.

Cheers,
Chao
